### PR TITLE
[FIX] Use log scale for chla plot for quenching assess

### PR DESCRIPTION
**Pull request by MOchiara**
This way we can better visualize if there is quenching or not (chla range can be big and then we cannot see much)

### CODE REVIEW

**Comment by MOchiara** [comment]
This way we can see quenching 
image

Otherwis, it is quite invisible
image

**Comment by MOchiara** [comment]
Size is the same in the fig but the screenshot is small because it was in my test notebook

**Review by callumrollo — CHANGES_REQUESTED** [review]
I like the change to the plot! The label needs to be fixed though. I think it should represent the actual equation something like:

log10(chlorophyll concentration) [mg m-3] 

sorry, no subscript in github comments! 

Also, I beleive that np.log defaults to the natural logarith, that is base _e_ rather than base 10, you should check

**Comment by MOchiara** [comment]
Ah I see! I though np.log was log10. I will check now

**Review by callumrollo — APPROVED** [review]

**Pull request merged**
